export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_IN_SUCCESS = 'SIG_IN_SUCCESS';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const VERIFY_TOKEN_SUCCESS = 'VERIFY_TOKEN_SUCCESS';

export const UNIVERSAL_MESSAGE = 'UNIVERSAL_MESSAGE';